Added new fields to the profiles table
CodeYourFuture/scot-min-imece pull request #20
Opened 2020-11-17 21:28 UTC by AaishaMohamad

2020-11-17 22:24 UTC, tekul requested changes
Nice work :smile_cat: :1st_place_medal: .

2020-11-17 22:24 UTC, tekul commented on server/db/recreate-schema.sql
> +CREATE TYPE type AS ENUM ('volunteer', 'service_user');
Maybe call this `profile_type` rather than just `type`.

2020-11-17 22:24 UTC, tekul commented on server/db/recreate-schema.sql
> +
Could you delete this extra space? Try not to add random space in files :slightly_smiling_face:.

2020-11-17 22:24 UTC, tekul commented on server/db/recreate-schema.sql
> +  join_date       DATE,
The `status` and `join_date` columns should probably be `NOT NULL` too.

2020-11-19 23:01 UTC, bonboh approved these changes
Great job @AaishaMohamad!

2020-11-19 23:01 UTC, merged